buildings:
  - Hatchery
  - Lair
  - Hive
  - Extractor
  - ExtractorRich
  - SpawningPool
  - EvolutionChamber
  - RoachWarren
  - BanelingNest
  - HydraliskDen
  - LurkerDenMP
  - InfestationPit
  - Spire
  - GreaterSpire
  - NydusNetwork
  - NydusCanal
  - UltraliskCavern
  - SpineCrawler
  - SporeCrawler
  - CreepTumor
  - CreepTumorBurrowed
  - CreepTumorQueen

workers:
  - Drone

basic_army:
  - Zergling
  - Baneling
  - Roach
  - Hydralisk

key_units:
  - Queen
  - Ravager
  - LurkerMP
  - Mutalisk
  - Corruptor
  - BroodLord
  - SwarmHostMP
  - Infestor
  - Viper
  - Ultralisk
  - Overlord
  - Overseer
  - OverlordTransport
  - NydusWorm

ignored:
  - Larva
  - Egg
  - Cocoon
  - BanelingCocoon
  - RavagerCocoon
  - LurkerMPEgg
  - BroodLordCocoon
  - OverlordCocoon
  - TransportOverlordCocoon
  - LocustMP
  - LocustMPFlying
  - Broodling
  - BroodlingEscort
  - InfestedTerran
  - InfestedTerransEgg
  - Changeling
  - ChangelingMarine
  - ChangelingMarineShield
  - ChangelingZealot
  - ChangelingZergling
  - ChangelingZerglingWings
  - ParasiticBombDummy
  - SpineCrawlerUprooted
  - SporeCrawlerUprooted
  - BeaconArmy
  - BeaconDefend
  - BeaconAttack
  - BeaconHarass
  - BeaconIdle
  - BeaconAuto
  - BeaconDetect
  - BeaconScout
  - BeaconClaim
  - BeaconExpand
  - BeaconRally
  - BeaconCustom1
  - BeaconCustom2
  - BeaconCustom3
  - BeaconCustom4
