buildings:
  - CommandCenter
  - OrbitalCommand
  - PlanetaryFortress
  - SupplyDepot
  - SupplyDepotLowered
  - Refinery
  - RefineryRich
  - Barracks
  - Factory
  - Starport
  - EngineeringBay
  - Armory
  - GhostAcademy
  - FusionCore
  - Bunker
  - MissileTurret
  - SensorTower
  - TechLab
  - Reactor
  - BarracksTechLab
  - FactoryTechLab
  - StarportTechLab
  - BarracksReactor
  - FactoryReactor
  - StarportReactor

workers:
  - SCV
  - MULE

basic_army:
  - Marine
  - Marauder

key_units:
  - Reaper
  - Hellion
  - Hellbat
  - Cyclone
  - WidowMine
  - SiegeTank
  - Medivac
  - VikingFighter
  - Raven
  - Liberator
  - Thor
  - Ghost
  - Battlecruiser

ignored:
  - KD8Charge
  - AutoTurret
  - PointDefenseDrone
  - Interceptor
  - LiberatorAG
  - SiegeTankSieged
  - Viking
  - VikingAssault
  - WidowMineBurrowed
  - BeaconArmy
  - BeaconDefend
  - BeaconAttack
  - BeaconHarass
  - BeaconIdle
  - BeaconAuto
  - BeaconDetect
  - BeaconScout
  - BeaconClaim
  - BeaconExpand
  - BeaconRally
  - BeaconCustom1
  - BeaconCustom2
  - BeaconCustom3
  - BeaconCustom4
  - BarracksFlying
  - FactoryFlying
  - StarportFlying
  - CommandCenterFlying
  - OrbitalCommandFlying
