buildings:
  - Nexus
  - Pylon
  - Assimilator
  - AssimilatorRich
  - Gateway
  - WarpGate
  - Forge
  - CyberneticsCore
  - RoboticsFacility
  - RoboticsBay
  - Stargate
  - FleetBeacon
  - TwilightCouncil
  - TemplarArchive
  - DarkShrine
  - PhotonCannon
  - ShieldBattery
  - StasisTrap

workers:
  - Probe

basic_army:
  - Zealot
  - Stalker
  - Adept

key_units:
  - Sentry
  - HighTemplar
  - DarkTemplar
  - Archon
  - Immortal
  - Colossus
  - Disruptor
  - Observer
  - WarpPrism
  - Phoenix
  - Oracle
  - VoidRay
  - Tempest
  - Carrier
  - Mothership
  - MothershipCore

ignored:
  - Interceptor
  - AdeptPhaseShift
  - DisruptorPhased
  - ObserverSiegeMode
  - OracleStasisTrap
  - WarpPrismPhasing
  - BeaconArmy
  - BeaconDefend
  - BeaconAttack
  - BeaconHarass
  - BeaconIdle
  - BeaconAuto
  - BeaconDetect
  - BeaconScout
  - BeaconClaim
  - BeaconExpand
  - BeaconRally
  - BeaconCustom1
  - BeaconCustom2
  - BeaconCustom3
  - BeaconCustom4
